[IO_INFORMATION]
# training dir, models are here under /models folder
train_dir = ../training  
# path to the training set
data_dir = ../datasets/training_set
# path to validation set
val_data_dir = ../../dia_1k/datasets/test_set
# set True if you would like to restart a training 
load_weights = True
# uncomment if you would like to start from a specific epoch
#weights_file = models/epoch_2110_step_2110000.pkl
# how frequently to save the model
save_epoch_freq = 50
# for accelerating the training
data_cache = True
task = val
val_dir = ./
[DATA_INFORMATION]
# list of elements present in training set
atomic_sequence = C
input_format = example   
output_offset = -253.67376683573406 

[MODEL_INFORMATION]
## Our standard model
model_type = MLP
## Architecture: l1:l2:l3
architecture = 16:8:1
# which descriptor, PANNA or LATTE
descriptor_type = LATTE
# more technical details, leave them as they are
nn_mode = list
pair_mod = 500
at_mod = 50
# the radius of atomic interaction
Rc = 5.0
sig = 1.0
# number of n-body interactions
descriptor_shape = 10,-:10,i,i:20,ij,ij:20,i,j,ij

[TRAINING_PARAMETERS]
#Batch size, too big might run out of memory
batch_size = 4
#Learning rate: you can concatenate schedules with a comma, this is just an example:
#const:lr:st means use learning rate lr for st number of steps
#exp:lr:dec:st means start from lr and decay by dec in st steps.
#So the following string trains with learning rate 1e-3 decaying to 1e-4 after 100k steps,then constant 1e-4 in 500k more steps
learning_rate = exp:1e-3:1e-1:100000, const:1e-4:500000
#L1 regularization, you can try a value around this one, from 0.001 to 0.0009
l1_coef = 0.001
#Total number of "epochs"
max_epochs = 250
#How many steps make an epoch
steps_per_epoch = 100
#Forces cost
forces_cost = 1.0
#Energy cost
energy_cost = 10.0
#This uses the energy square loss per atom in the loss function
energy_loss = per_at
