#!/bin/bash
#SBATCH -A IscrC_UQ4ML
#SBATCH -p boost_usr_prod
#SBATCH --output=out
#SBATCH --open-mode=append
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mem=100000MB
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --job-name=carbon
#SBATCH --time 22:50:00

touch $SLURM_JOB_ID


# Load environment
source /leonardo/pub/userexternal/fpelleg1/panna_jax_release/panna_venv/bin/activate

# Your commands here
date
python3 /leonardo/pub/userexternal/fpelleg1/panna_jax_release/panna_code/src/panna/train_jax.py -c train.ini
date

