[IO_INFORMATION]
train_dir = train_diverse
data_dir = /leonardo/pub/userexternal/mtaleblo/Carbon_trainings/div_5k/datasets/training_set
val_data_dir = /leonardo/pub/userexternal/mtaleblo/Carbon_trainings/div_5k/datasets/validation_set
data_cache = True
load_weights = True
#weights_file = models/epoch_xx_step_yy.pkl
metrics = MAE
save_epoch_freq = 10

[DATA_INFORMATION]
# Possible options: example, spice, npy
input_format = example
atomic_sequence = C
output_offset = -253.68 

[MODEL_INFORMATION]
model_type = MLP
architecture = 64:32:1
# One per layer: c=common, e=embedded, s=species_specific (default: all s)
#mlp_sp_weights = c:c:c
descriptor_type = LATTE
at_mod = 50
pair_mod = 500
Rc = 5.0
# Descriptor can be: common or specific (default)
#spec_weights = common
# Species embedding file (if present, uses embedding in descriptor)
#sp_emb_file = ../matscholar_dict.pkl
# Whether to embed the central atom (makes sense with common and embedding)
#center_atom_emb = True
# One value if sigma is fixed
sig = 1.0
# Two values if we want to learn sigma, and option learsig=True
#sig = 0.1,2.0
#learnsig = True
descriptor_shape = 50,-:50,a,a:50,a,ab,b

[TRAINING_PARAMETERS]
batch_size = 64
learning_rate = const:1e-3:1000000,exp:1e-3:1e-5:1000000
l1_coef = 0.001
max_epochs = 2000
steps_per_epoch = 1000
forces_cost = 100.0
energy_loss = per_at
energy_cost = 100.0

